apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment-latest
  namespace: preprod
  labels:
    app: app1-latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-latest
  template:
    metadata:
      labels:
        app: app1-latest
    spec:
      containers:
        - name: app1-latest
          image: app1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "100m"
