apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress-canary
  namespace: preprod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "40"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: app1-service-latest
            port:
              number: 80